/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estructurasdedatos;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jclav
 */
public class Carreras_Universidades extends javax.swing.JFrame {
    

     class Node {

        String key[] = new String[7];
        int height;
        Node left, right;

        Node(String d[]) {
            key = d;
            height = 1;
        }
    }
     
    QueueRef cola = new QueueRef();
    QueueRef_Colas colas = new QueueRef_Colas();
    ArbolAvlArrays tree = new ArbolAvlArrays();
    
    public Carreras_Universidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Universidad_txt = new javax.swing.JTextField();
        Direccion_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Carrera_txt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nombre_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/-background-and-red--image.jpg"))); // NOI18N
        jLabel4.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Universidad1", "Carrera1", "Universidad2", "Carrera2", "Nombre", "Apellido", "Nid"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 860, 420));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("Encontrar archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 170, 40));

        Universidad_txt.setText("Ingrese el nombre de la Universidad");
        Universidad_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Universidad_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Universidad_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 260, 40));

        Direccion_txt.setText("Ingrese la direccion del archivo");
        Direccion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Direccion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, 40));

        jLabel8.setText("Carrera Consulta");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jLabel3.setText("Universidad Consulta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, -1, -1));

        Carrera_txt.setText("Ingrese el nombre de la carrera");
        Carrera_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrera_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Carrera_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 260, 40));

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 170, 40));

        jButton2.setText("Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 170, 40));

        nombre_txt.setText("Ingrese el nombre del postulante");
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 260, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-polygonal-banner-background-and-red-geometry-image_319850.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, 620));

        jLabel9.setText("Buscar por nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-polygonal-banner-background-and-red-geometry-image_319850.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngtree-polygonal-banner-background-and-red-geometry-image_319850.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        BufferedReader lector; //Leer archivo
        String linea;  //Recibe cada fila
        String partes[] = null;  //Almacena cada linea leida
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Universidad1");
        model.addColumn("Carrera1");
        model.addColumn("Universidad2");
        model.addColumn("Carrera2");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("NID");

        try {
            lector = new BufferedReader(new FileReader(Direccion_txt.getText()));
            while ((linea = lector.readLine()) != null) {
                QueueRef cola = new QueueRef();
                partes = linea.split(",");

                model.addRow(new Object[]{partes[0], partes[1], partes[2], partes[3], partes[4], partes[5], partes[6]});
               
               /*
                Ingreso de datos con colas : 
                
                cola.push(partes[0]);
                cola.push(partes[1]);
                cola.push(partes[2]);
                cola.push(partes[3]);
                cola.push(partes[4]);
                cola.push(partes[5]);
                cola.push(partes[6]);
                
                colas.push(cola);
                 */
               
                tree.root = tree.insert(tree.root, partes);
                
            }
            

            lector.close();
            linea = null;
            partes = null;

            jTable1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        tree.preOrder(tree.root);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Direccion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Direccion_txtActionPerformed

    private void Universidad_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Universidad_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Universidad_txtActionPerformed

    private void Carrera_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrera_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carrera_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String carrera = Carrera_txt.getText();
        String universidad = Universidad_txt.getText();
        
        int N_universidad = 0;
        int N_carrera = 0;

        /*
        while (!colas.empty()){
            QueueRef cola = new QueueRef();
            cola = colas.pop();
          
            if (universidad.equals(cola.pop())) {

                N_universidad = N_universidad + 1;

            }

            if (carrera.equals(cola.pop())) {

                N_carrera = N_carrera + 1;

            }

            if (universidad.equals(cola.pop())) {

                N_universidad = N_universidad + 1;

            }
            if (carrera.equals(cola.pop())) {

                N_carrera = N_carrera + 1;

            }

        }*/
        
        
       N_carrera = tree.Contar_carreras(tree.root, carrera);
       N_universidad = tree.Contar_universidades(tree.root,universidad);
         
       String num_c = String.valueOf(N_carrera);
       String num_u = String.valueOf(N_universidad);
        
       Carrera_txt.setText(num_c);
       Universidad_txt.setText(num_u);
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String nombre = nombre_txt.getText();
        String datos = tree.Shearch(tree.root, nombre);
        nombre_txt.setText(datos);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Main_Menu prov = new Main_Menu();
        prov.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carreras_Universidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carreras_Universidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carreras_Universidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carreras_Universidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Carreras_Universidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Carrera_txt;
    private javax.swing.JTextField Direccion_txt;
    private javax.swing.JTextField Universidad_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre_txt;
    // End of variables declaration//GEN-END:variables
}
